"""scale_metrics_schema

Revision ID: 7fc7fde26ada
Revises: 7c339c69ebbc
Create Date: 2026-07-19 14:14:08.074737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc7fde26ada'
down_revision: Union[str, Sequence[str], None] = '7c339c69ebbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('qlike_score', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('ci_lower_bound', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('ci_upper_bound', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'ci_upper_bound')
    op.drop_column('predictions', 'ci_lower_bound')
    op.drop_column('predictions', 'qlike_score')
    # ### end Alembic commands ###
